// <auto-generated />
namespace WhatToDo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RecHabitAvgMiss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecHabitAvgMiss));
        
        string IMigrationMetadata.Id
        {
            get { return "202107261113519_RecHabitAvgMiss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
